artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:  artifacts/data_ingestion/
  local_data_file1: artifacts/data_ingestion/data.parquet

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data.parquet
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/data.parquet
  data_file_path : artifacts/data_ingestion/

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/
  test_data_path: artifacts/data_ingestion/
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_ingestion/
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json